"""Chat state — Phase 2 UI behavior only.

The message list, composer, pending/loading/error states, and clear-chat
confirmation flow all live here. Assistant replies are generated by a
local, deterministic stub (`_local_reply`) that mimics the shape of what
the real `agent.graph.run_agent` returns — item / amount / category /
meta line / optional alert — so the UI can be built and reviewed
without touching the LangGraph agent yet.

Phase 3 will:
  * import `agent.graph.run_agent` and call it from `send_message`
    (probably inside an `async` background event so the composer can
    show a real pending state during LLM latency),
  * replace `_local_reply` with the agent's response,
  * hydrate `user_id` from `AuthState.user_email` and pass it through,
  * carry `pending_edit` / `pending_conversion` across turns exactly
    like `app.py` already does today.

Keeping the field names identical to what `agent.state.AgentState`
exposes (`item`, `amount`, `category`, `pending_edit`,
`pending_conversion`) means the phase 3 wiring is a straight pass-through
rather than a re-mapping.
"""

import re
from datetime import datetime
from typing import TypedDict

import reflex as rx

import logging


class ChatMessage(TypedDict):
    role: str  # "user" | "assistant"
    text: str
    meta: str  # e.g. "Food • ₱85 • Today" — empty string when not applicable
    time: str  # rendered timestamp, HH:MM AM/PM
    alert: str  # "" | "warning" | "danger"


PROMPT_CHIPS: list[str] = [
    "milk tea ₱85",
    "grab ride 240",
    "how much this week?",
    "set food budget to 3000",
]


# Rough category guesses used only by the local stub. The real agent has
# a proper LLM-backed classifier — this is just enough to make the UI
# feel alive during phase 2.
_LOCAL_CATEGORY_HINTS: dict[str, list[str]] = {
    "Food": [
        "coffee",
        "milk tea",
        "fries",
        "lunch",
        "dinner",
        "breakfast",
        "snack",
        "rice",
    ],
    "Transport": ["grab", "taxi", "ride", "jeep", "bus", "gas", "fuel"],
    "Bills": ["electricity", "water", "internet", "rent", "bill"],
    "Shopping": ["shirt", "shoes", "case", "phone", "clothes"],
    "Entertainment": ["movie", "netflix", "game", "concert"],
    "Health": ["pharmacy", "medicine", "doctor", "clinic"],
    "Personal Care": ["haircut", "salon", "soap"],
}

_AMOUNT_PATTERN = re.compile(
    r"(?:₱|php\s*|p\s*|\$)?\s*(\d+(?:\.\d{1,2})?)", re.IGNORECASE
)


def _guess_category(item: str) -> str:
    lower = item.lower()
    for cat, keywords in _LOCAL_CATEGORY_HINTS.items():
        if any(k in lower for k in keywords):
            return cat
    return "Other"


def _looks_like_purchase(message: str) -> tuple[str, float] | None:
    """Best-effort local extractor: returns (item, amount) or None.
    Deliberately much simpler than the real LLM extractor — phase 3
    replaces this with `run_agent`."""
    match = _AMOUNT_PATTERN.search(message)
    if not match:
        return None
    try:
        amount = float(match.group(1))
    except ValueError:
        return None
    if amount <= 0:
        return None
    # Strip the amount + currency markers to guess the item name.
    item = _AMOUNT_PATTERN.sub("", message, count=1)
    item = re.sub(
        r"\b(bought|for|paid|got|grabbed|a|an|the|php|peso|pesos)\b",
        "",
        item,
        flags=re.IGNORECASE,
    )
    item = item.strip(" ,.-").strip()
    if not item:
        return None
    return item, amount


class ChatState(rx.State):
    messages: list[ChatMessage] = []
    draft: str = ""
    # Bumped only when we programmatically overwrite the composer (prompt
    # chip click, chat clear). Bound to the input's `key` prop so the
    # element only remounts on those explicit resets — typing itself
    # never remounts the input, preserving cursor position and focus.
    draft_version: int = 0

    # Pending / loading / error state for the composer.
    is_sending: bool = False
    error_text: str = ""

    # Clear-chat confirmation flow (mirrors the Streamlit "Cancel/Confirm"
    # pattern so the destructive action always takes two clicks).
    confirm_clear: bool = False

    # Carried across turns for phase 3 wiring — see module docstring.
    pending_edit: dict[str, str] = {}
    pending_conversion: dict[str, str] = {}

    @rx.var
    def has_messages(self) -> bool:
        return len(self.messages) > 0

    @rx.var
    def message_count(self) -> int:
        return len(self.messages)

    @rx.event
    def set_draft(self, value: str):
        self.draft = value

    @rx.event
    def dismiss_error(self):
        self.error_text = ""

    @rx.event
    def use_prompt(self, prompt: str):
        """Fill the composer with a suggested prompt chip."""
        self.draft = prompt
        self.draft_version += 1
        self.error_text = ""

    @rx.event
    def request_clear(self):
        self.confirm_clear = True

    @rx.event
    def cancel_clear(self):
        self.confirm_clear = False

    @rx.event
    def confirm_clear_chat(self):
        self.messages = []
        self.confirm_clear = False
        self.error_text = ""
        self.pending_edit = {}
        self.pending_conversion = {}
        self.draft = ""
        self.draft_version += 1

    @rx.event
    def send_message(self, form_data: dict[str, str]):
        """Push a user message + generate a local assistant reply.

        Phase 3 replaces the body of this handler with a call to
        `agent.graph.run_agent(AuthState.user_email, prompt)` (wrapped in
        a background task so the pending-state spinner is meaningful).
        """
        prompt = (form_data.get("draft") or self.draft or "").strip()
        if not prompt:
            self.error_text = "Type something first — even 'coffee 150' works."
            return

        if self.is_sending:
            # Guard against double-submit while a reply is pending.
            return

        now = datetime.now().strftime("%I:%M %p").lstrip("0")

        self.messages.append(
            ChatMessage(role="user", text=prompt, meta="", time=now, alert="")
        )
        self.draft = ""
        self.draft_version += 1
        self.error_text = ""
        self.is_sending = True
        yield  # flush the user message + pending state before generating the reply

        try:
            reply_text, meta, alert = self._local_reply(prompt)
        except Exception as e:  # keep the UI resilient regardless of stub logic
            logging.exception("Unexpected error")
            reply_text = "Something went sideways on my end. Try again?"
            meta = ""
            alert = "danger"
            self.error_text = f"Local preview error: {e}"

        self.messages.append(
            ChatMessage(
                role="assistant",
                text=reply_text,
                meta=meta,
                time=now,
                alert=alert,
            )
        )
        self.is_sending = False

    def _local_reply(self, prompt: str) -> tuple[str, str, str]:
        """Deterministic Phase-2 stub. Returns (text, meta, alert)."""
        lower = prompt.lower().strip()

        if (
            any(g in lower for g in ("hi", "hello", "hey", "yo ", "sup"))
            and len(lower) < 20
        ):
            return (
                "Hey! Tell me what you bought and I'll log it. "
                "Try something like 'milk tea 85' or 'grab ride 240'.",
                "",
                "",
            )

        if "budget" in lower and ("set" in lower or "change" in lower):
            return (
                "Budgets get set once we wire the agent up in the next phase — "
                "for now, you can preview how the confirmation will look.",
                "Preview only",
                "",
            )

        if any(q in lower for q in ("how much", "spent", "spending", "left")):
            return (
                "In the shipped app I'd pull this from your transactions — "
                "for the phase 2 preview, imagine ₱2,450 spent this week, "
                "mostly on Food. 🍽️",
                "Preview only",
                "",
            )

        purchase = _looks_like_purchase(prompt)
        if purchase is None:
            return (
                "I didn't catch a purchase in that. Try 'coffee 150' or "
                "'bought a phone case for 350'.",
                "",
                "",
            )

        item, amount = purchase
        category = _guess_category(item)
        meta = f"{category} • ₱{amount:,.0f} • Today"

        text = f"Logged: {item} — ₱{amount:,.2f} ({category})"
        alert = ""
        # Toy budget alert so the warning treatment can be reviewed in Phase 2.
        if category == "Food" and amount >= 500:
            text += "\n\n⚠️ Heads up — this one's a big chunk of a typical Food budget."
            alert = "warning"
        elif amount >= 5000:
            text += "\n\n⚠️ Big purchase — the real agent will check this against your budgets."
            alert = "warning"

        return text, meta, alert
